export const questionData = {
    English: [
{ q: "Choose the correct plural of 'child'", a: ["childs", "children", "childes", "childrens"], correct: 1 },
{ q: "Which word is a noun?", a: ["run", "blue", "happiness", "quickly"], correct: 2 },
{ q: "Opposite of 'hot' is:", a: ["warm", "cold", "heat", "fire"], correct: 1 },
{ q: "Choose the correct article: ___ apple", a: ["a", "an", "the", "no article"], correct: 1 },
{ q: "Which is a verb?", a: ["teacher", "sing", "happy", "book"], correct: 1 },
{ q: "Past tense of 'go' is:", a: ["goed", "go", "went", "gone"], correct: 2 },
{ q: "Which word is an adjective?", a: ["run", "beautiful", "quickly", "eat"], correct: 1 },
{ q: "Plural of 'mouse' is:", a: ["mouses", "mouse", "mice", "meese"], correct: 2 },
{ q: "Correct spelling:", a: ["recieve", "receive", "receeve", "receiv"], correct: 1 },
{ q: "Which is a pronoun?", a: ["boy", "book", "he", "school"], correct: 2 },

{ q: "Opposite of 'tall' is:", a: ["big", "short", "long", "small"], correct: 1 },
{ q: "Which sentence is correct?", a: ["She go to school", "She goes to school", "She going school", "She gone school"], correct: 1 },
{ q: "Which is a vowel?", a: ["b", "c", "a", "d"], correct: 2 },
{ q: "Past tense of 'eat' is:", a: ["eated", "ate", "eats", "eaten"], correct: 1 },
{ q: "Which word means 'very big'?", a: ["tiny", "huge", "small", "short"], correct: 1 },
{ q: "Choose the correct preposition: The cat is ___ the table", a: ["on", "in", "at", "by"], correct: 0 },
{ q: "Plural of 'man' is:", a: ["mans", "men", "man", "mens"], correct: 1 },
{ q: "Which is an action word?", a: ["sleep", "bed", "room", "chair"], correct: 0 },
{ q: "Opposite of 'happy' is:", a: ["glad", "sad", "smile", "joy"], correct: 1 },
{ q: "Which is a sentence?", a: ["Running fast", "He runs fast", "Fast running", "Runs fast"], correct: 1 },

{ q: "Which word is a conjunction?", a: ["and", "run", "big", "table"], correct: 0 },
{ q: "Choose the correct plural of 'tooth'", a: ["tooths", "teeth", "toothes", "tooth"], correct: 1 },
{ q: "Which is a proper noun?", a: ["city", "boy", "India", "school"], correct: 2 },
{ q: "Past tense of 'see' is:", a: ["seed", "saw", "seen", "see"], correct: 1 },
{ q: "Which word describes a noun?", a: ["verb", "adjective", "pronoun", "conjunction"], correct: 1 },
{ q: "Opposite of 'open' is:", a: ["lock", "close", "shut", "stop"], correct: 1 },
{ q: "Which is a question word?", a: ["because", "what", "and", "but"], correct: 1 },
{ q: "Choose the correct sentence:", a: ["He don't like apples", "He doesn't like apples", "He not like apples", "He no like apples"], correct: 1 },
{ q: "Plural of 'foot' is:", a: ["foots", "feet", "footes", "foot"], correct: 1 },
{ q: "Which word is an adverb?", a: ["slow", "slowly", "slowness", "slowed"], correct: 1 },

{ q: "Opposite of 'early' is:", a: ["fast", "soon", "late", "quick"], correct: 2 },
{ q: "Which is a punctuation mark?", a: ["comma", "letter", "word", "sentence"], correct: 0 },
{ q: "Choose the correct verb: She ___ singing", a: ["is", "are", "were", "be"], correct: 0 },
{ q: "Which word means 'not correct'?", a: ["right", "true", "wrong", "good"], correct: 2 },
{ q: "Plural of 'leaf' is:", a: ["leafs", "leaves", "leaf", "leavs"], correct: 1 },
{ q: "Which sentence is in past tense?", a: ["I eat rice", "I ate rice", "I will eat rice", "I am eating rice"], correct: 1 },
{ q: "Opposite of 'near' is:", a: ["close", "far", "here", "there"], correct: 1 },
{ q: "Which is a helping verb?", a: ["run", "is", "eat", "jump"], correct: 1 },
{ q: "Choose the correct article: ___ elephant", a: ["a", "an", "the", "no article"], correct: 1 },
{ q: "Which word is a naming word?", a: ["run", "boy", "fast", "very"], correct: 1 },

{ q: "Plural of 'woman' is:", a: ["womans", "women", "woman", "womens"], correct: 1 },
{ q: "Which sentence shows future tense?", a: ["I eat", "I ate", "I will eat", "I am eating"], correct: 2 },
{ q: "Opposite of 'strong' is:", a: ["powerful", "weak", "hard", "tough"], correct: 1 },
{ q: "Which is a correct sentence?", a: ["She are happy", "She is happy", "She am happy", "She be happy"], correct: 1 },
{ q: "Which word is a describing word?", a: ["red", "run", "eat", "play"], correct: 0 },
{ q: "Plural of 'bus' is:", a: ["buses", "bus", "buss", "buseses"], correct: 0 },
{ q: "Which word joins sentences?", a: ["noun", "verb", "conjunction", "pronoun"], correct: 2 },
{ q: "Opposite of 'clean' is:", a: ["pure", "dirty", "wash", "neat"], correct: 1 },
{ q: "Which word is a sound word?", a: ["bang", "walk", "blue", "table"], correct: 0 },
{ q: "Which sentence ends with a question mark?", a: ["I like apples", "Do you like apples?", "I like apples!", "I like apples."], correct: 1 }
],

    Hindi: [
{ q: "'लड़का' का बहुवचन क्या है?", a: ["लड़की", "लड़के", "लड़कों", "लड़कियाँ"], correct: 1 },
{ q: "'खाना' किस प्रकार का शब्द है?", a: ["संज्ञा", "सर्वनाम", "क्रिया", "विशेषण"], correct: 2 },
{ q: "'दिन' का विलोम शब्द क्या है?", a: ["सुबह", "शाम", "रात", "दोपहर"], correct: 2 },
{ q: "'सुंदर' किसका उदाहरण है?", a: ["संज्ञा", "क्रिया", "विशेषण", "सर्वनाम"], correct: 2 },
{ q: "'मैं' कौन सा शब्द है?", a: ["संज्ञा", "सर्वनाम", "क्रिया", "विशेषण"], correct: 1 },
{ q: "'दौड़ना' किस प्रकार का शब्द है?", a: ["संज्ञा", "क्रिया", "विशेषण", "अव्यय"], correct: 1 },
{ q: "'पेड़' क्या है?", a: ["क्रिया", "संज्ञा", "सर्वनाम", "विशेषण"], correct: 1 },
{ q: "'अच्छा' का विलोम शब्द क्या है?", a: ["खराब", "सुंदर", "बड़ा", "छोटा"], correct: 0 },
{ q: "'हम' कौन सा शब्द है?", a: ["संज्ञा", "सर्वनाम", "क्रिया", "विशेषण"], correct: 1 },
{ q: "'लिखना' क्या है?", a: ["संज्ञा", "क्रिया", "विशेषण", "अव्यय"], correct: 1 },

{ q: "'कुत्ता' का बहुवचन क्या है?", a: ["कुत्ते", "कुत्तों", "कुतिया", "कुत्तियाँ"], correct: 0 },
{ q: "'जल' का अर्थ क्या है?", a: ["आग", "हवा", "पानी", "धरती"], correct: 2 },
{ q: "'खुश' का विलोम शब्द क्या है?", a: ["प्रसन्न", "आनंदित", "दुखी", "हँसमुख"], correct: 2 },
{ q: "'लाल' किस प्रकार का शब्द है?", a: ["संज्ञा", "क्रिया", "विशेषण", "सर्वनाम"], correct: 2 },
{ q: "'वह' कौन सा शब्द है?", a: ["संज्ञा", "सर्वनाम", "क्रिया", "विशेषण"], correct: 1 },
{ q: "'सोना' किस प्रकार का शब्द है? (नींद)", a: ["संज्ञा", "क्रिया", "विशेषण", "अव्यय"], correct: 1 },
{ q: "'पुस्तक' क्या है?", a: ["क्रिया", "संज्ञा", "सर्वनाम", "विशेषण"], correct: 1 },
{ q: "'ऊँचा' का विलोम शब्द क्या है?", a: ["लंबा", "छोटा", "नीचा", "मोटा"], correct: 2 },
{ q: "'वे' कौन सा शब्द है?", a: ["संज्ञा", "सर्वनाम", "क्रिया", "विशेषण"], correct: 1 },
{ q: "'खेलना' क्या है?", a: ["संज्ञा", "क्रिया", "विशेषण", "अव्यय"], correct: 1 },

{ q: "'गाय' का बहुवचन क्या है?", a: ["गायें", "गाय", "गायों", "गइयाँ"], correct: 0 },
{ q: "'घर' क्या है?", a: ["क्रिया", "संज्ञा", "सर्वनाम", "विशेषण"], correct: 1 },
{ q: "'सत्य' का विलोम शब्द क्या है?", a: ["सही", "गलत", "अच्छा", "नया"], correct: 1 },
{ q: "'मीठा' किस प्रकार का शब्द है?", a: ["संज्ञा", "क्रिया", "विशेषण", "सर्वनाम"], correct: 2 },
{ q: "'तुम' कौन सा शब्द है?", a: ["संज्ञा", "सर्वनाम", "क्रिया", "विशेषण"], correct: 1 },
{ q: "'पढ़ना' क्या है?", a: ["संज्ञा", "क्रिया", "विशेषण", "अव्यय"], correct: 1 },
{ q: "'नदी' क्या है?", a: ["क्रिया", "संज्ञा", "सर्वनाम", "विशेषण"], correct: 1 },
{ q: "'अंधेरा' का विलोम शब्द क्या है?", a: ["काला", "उजाला", "रात", "दिन"], correct: 1 },
{ q: "'ये' कौन सा शब्द है?", a: ["संज्ञा", "सर्वनाम", "क्रिया", "विशेषण"], correct: 1 },
{ q: "'चलना' क्या है?", a: ["संज्ञा", "क्रिया", "विशेषण", "अव्यय"], correct: 1 },

{ q: "'फल' क्या है?", a: ["क्रिया", "संज्ञा", "सर्वनाम", "विशेषण"], correct: 1 },
{ q: "'काला' किस प्रकार का शब्द है?", a: ["संज्ञा", "क्रिया", "विशेषण", "सर्वनाम"], correct: 2 },
{ q: "'सूरज' का अर्थ क्या है?", a: ["चाँद", "तारा", "सूर्य", "ग्रह"], correct: 2 },
{ q: "'हँसना' क्या है?", a: ["संज्ञा", "क्रिया", "विशेषण", "अव्यय"], correct: 1 },
{ q: "'बड़ा' का विलोम शब्द क्या है?", a: ["लंबा", "ऊँचा", "छोटा", "मोटा"], correct: 2 },
{ q: "'हमारा' कौन सा शब्द है?", a: ["संज्ञा", "सर्वनाम", "क्रिया", "विशेषण"], correct: 1 },
{ q: "'दूध' क्या है?", a: ["क्रिया", "संज्ञा", "सर्वनाम", "विशेषण"], correct: 1 },
{ q: "'तेज़' किस प्रकार का शब्द है?", a: ["संज्ञा", "क्रिया", "विशेषण", "सर्वनाम"], correct: 2 },
{ q: "'वे खेलते हैं' में क्रिया कौन सी है?", a: ["वे", "खेलते", "हैं", "दोनों"], correct: 1 },
{ q: "'दिन' किसका उदाहरण है?", a: ["संज्ञा", "क्रिया", "विशेषण", "सर्वनाम"], correct: 0 }
],

    French: [
{ q: "What is 'apple' in French?", a: ["pomme", "banane", "orange", "raisin"], correct: 0 },
{ q: "What does 'bonjour' mean?", a: ["Good night", "Hello", "Goodbye", "Thanks"], correct: 1 },
{ q: "Plural of 'livre' is:", a: ["livre", "livres", "livrés", "livrent"], correct: 1 },
{ q: "What is 'dog' in French?", a: ["chat", "chien", "oiseau", "vache"], correct: 1 },
{ q: "Meaning of 'merci'?", a: ["Sorry", "Please", "Thanks", "Hello"], correct: 2 },
{ q: "Which is a verb?", a: ["manger", "pomme", "rouge", "livre"], correct: 0 },
{ q: "What is 'red' in French?", a: ["vert", "bleu", "rouge", "noir"], correct: 2 },
{ q: "What is the article for 'école'?", a: ["le", "la", "les", "un"], correct: 1 },
{ q: "What does 'au revoir' mean?", a: ["Hello", "Goodbye", "Please", "Thanks"], correct: 1 },
{ q: "Which is feminine?", a: ["le garçon", "le livre", "la fille", "le chien"], correct: 2 },

{ q: "What is 'cat' in French?", a: ["chien", "chat", "cheval", "oiseau"], correct: 1 },
{ q: "What is 'water' in French?", a: ["lait", "jus", "eau", "thé"], correct: 2 },
{ q: "Plural of 'chien' is:", a: ["chien", "chiens", "chienes", "chienss"], correct: 1 },
{ q: "What does 's'il vous plaît' mean?", a: ["Sorry", "Please", "Thanks", "Welcome"], correct: 1 },
{ q: "Which is masculine?", a: ["la table", "la porte", "le livre", "la chaise"], correct: 2 },
{ q: "What is 'blue' in French?", a: ["bleu", "vert", "noir", "rouge"], correct: 0 },
{ q: "What is 'school' in French?", a: ["école", "maison", "livre", "classe"], correct: 0 },
{ q: "Which word means 'to eat'?", a: ["boire", "manger", "aller", "voir"], correct: 1 },
{ q: "What is 'small' in French?", a: ["grand", "petit", "long", "haut"], correct: 1 },
{ q: "What is 'thank you very much'?", a: ["merci", "bonjour", "merci beaucoup", "au revoir"], correct: 2 },

{ q: "What is 'father' in French?", a: ["mère", "frère", "père", "oncle"], correct: 2 },
{ q: "What is 'mother' in French?", a: ["mère", "soeur", "tante", "fille"], correct: 0 },
{ q: "What is 'bread' in French?", a: ["riz", "pain", "fromage", "beurre"], correct: 1 },
{ q: "Which is a color?", a: ["chien", "vert", "livre", "table"], correct: 1 },
{ q: "What does 'oui' mean?", a: ["No", "Yes", "Maybe", "Hello"], correct: 1 },
{ q: "What does 'non' mean?", a: ["Yes", "No", "Thanks", "Please"], correct: 1 },
{ q: "What is 'house' in French?", a: ["maison", "école", "porte", "fenêtre"], correct: 0 },
{ q: "Plural of 'fille' is:", a: ["fille", "filles", "filla", "filles"], correct: 1 },
{ q: "Which means 'big'?", a: ["petit", "grand", "court", "bas"], correct: 1 },
{ q: "What is 'book' in French?", a: ["stylo", "livre", "table", "chaise"], correct: 1 },

{ q: "What is 'brother' in French?", a: ["frère", "soeur", "père", "oncle"], correct: 0 },
{ q: "What is 'sister' in French?", a: ["tante", "fille", "soeur", "mère"], correct: 2 },
{ q: "What is 'milk' in French?", a: ["eau", "lait", "jus", "thé"], correct: 1 },
{ q: "Which word means 'to drink'?", a: ["manger", "boire", "aller", "venir"], correct: 1 },
{ q: "What is 'green' in French?", a: ["bleu", "vert", "rouge", "jaune"], correct: 1 },
{ q: "What is 'yellow' in French?", a: ["jaune", "vert", "bleu", "noir"], correct: 0 },
{ q: "What does 'comment ça va' mean?", a: ["What is your name?", "How are you?", "Where are you?", "What time is it?"], correct: 1 },
{ q: "What is 'teacher' in French?", a: ["élève", "professeur", "ami", "père"], correct: 1 },
{ q: "What is 'student' in French?", a: ["professeur", "élève", "ami", "fils"], correct: 1 },
{ q: "What is 'friend' in French?", a: ["ami", "frère", "soeur", "voisin"], correct: 0 },

{ q: "What is 'car' in French?", a: ["vélo", "bus", "voiture", "train"], correct: 2 },
{ q: "What is 'school bag' in French?", a: ["cartable", "chaussure", "livre", "table"], correct: 0 },
{ q: "Which means 'fast'?", a: ["lent", "rapide", "petit", "bas"], correct: 1 },
{ q: "What is 'slow' in French?", a: ["rapide", "lent", "grand", "fort"], correct: 1 },
{ q: "What is 'window' in French?", a: ["porte", "mur", "fenêtre", "toit"], correct: 2 },
{ q: "What is 'door' in French?", a: ["porte", "fenêtre", "chaise", "table"], correct: 0 },
{ q: "Which means 'happy'?", a: ["triste", "content", "fatigué", "malade"], correct: 1 },
{ q: "Opposite of 'triste'?", a: ["content", "lent", "petit", "froid"], correct: 0 },
{ q: "What is 'cold' in French?", a: ["chaud", "froid", "sec", "humide"], correct: 1 },
{ q: "What is 'hot' in French?", a: ["froid", "chaud", "lent", "grand"], correct: 1 }
],

  Sanskrit: [
{ q: "'रामः' कः?", a: ["फलम्", "नरः", "नदी", "पुस्तकम्"], correct: 1 },
{ q: "'फलम्' किम्?", a: ["नरः", "स्त्री", "वस्तु", "पशुः"], correct: 2 },
{ q: "'गच्छति' शब्दस्य अर्थः कः?", a: ["खादति", "पठति", "गच्छति", "लिखति"], correct: 2 },
{ q: "'पठति' शब्दस्य अर्थः कः?", a: ["पढ़ता है", "खाता है", "सोता है", "दौड़ता है"], correct: 0 },
{ q: "'बालकः' कः?", a: ["स्त्री", "नरः", "फलम्", "वस्तु"], correct: 1 },
{ q: "'जलम्' किम्?", a: ["नरः", "स्त्री", "वस्तु", "पशुः"], correct: 2 },
{ q: "'सुन्दरः' शब्दः किम्?", a: ["संज्ञा", "क्रिया", "विशेषण", "सर्वनाम"], correct: 2 },
{ q: "'धावति' शब्दस्य अर्थः कः?", a: ["दौड़ता है", "खाता है", "सोता है", "पढ़ता है"], correct: 0 },
{ q: "'गजः' कः?", a: ["सिंहः", "अश्वः", "हस्ती", "वानरः"], correct: 2 },
{ q: "'नदी' शब्दस्य अर्थः कः?", a: ["पर्वतः", "नदी", "वनम्", "गृहम्"], correct: 1 },

{ q: "'क्रीडति' शब्दस्य अर्थः कः?", a: ["खेलता है", "सोता है", "पढ़ता है", "चलता है"], correct: 0 },
{ q: "'लिखति' शब्दस्य अर्थः कः?", a: ["लिखता है", "पढ़ता है", "खाता है", "सोता है"], correct: 0 },
{ q: "'बालिका' का अर्थ क्या है?", a: ["लड़का", "लड़की", "महिला", "बालक"], correct: 1 },
{ q: "'पुस्तकम्' किम्?", a: ["नरः", "स्त्री", "वस्तु", "पशुः"], correct: 2 },
{ q: "'खादति' शब्दस्य अर्थः कः?", a: ["खाता है", "पीता है", "दौड़ता है", "पढ़ता है"], correct: 0 },
{ q: "'वदति' शब्दस्य अर्थः कः?", a: ["सोता है", "बोलता है", "खाता है", "चलता है"], correct: 1 },
{ q: "'गायः' कः?", a: ["पशुः", "नरः", "स्त्री", "वस्तु"], correct: 0 },
{ q: "'अश्वः' कः?", a: ["हाथी", "घोड़ा", "गाय", "सिंह"], correct: 1 },
{ q: "'गृहं' किम्?", a: ["वनम्", "नदी", "घर", "पर्वतः"], correct: 2 },
{ q: "'पिबति' शब्दस्य अर्थः कः?", a: ["खाता है", "पीता है", "चलता है", "सोता है"], correct: 1 },

{ q: "'पठन्ति' शब्दः कः कालः?", a: ["वर्तमान", "भूत", "भविष्य", "आदेश"], correct: 0 },
{ q: "'अहं' किम्?", a: ["संज्ञा", "सर्वनाम", "क्रिया", "विशेषण"], correct: 1 },
{ q: "'त्वं' किम्?", a: ["संज्ञा", "सर्वनाम", "क्रिया", "अव्यय"], correct: 1 },
{ q: "'सः' किम्?", a: ["सर्वनाम", "क्रिया", "विशेषण", "संज्ञा"], correct: 0 },
{ q: "'सा' किम्?", a: ["संज्ञा", "सर्वनाम", "क्रिया", "अव्यय"], correct: 1 },
{ q: "'वनम्' किम्?", a: ["नदी", "पर्वतः", "वन", "गृह"], correct: 2 },
{ q: "'चलति' शब्दस्य अर्थः कः?", a: ["चलता है", "सोता है", "खाता है", "पढ़ता है"], correct: 0 },
{ q: "'तिष्ठति' शब्दस्य अर्थः कः?", a: ["खड़ा रहता है", "दौड़ता है", "सोता है", "खाता है"], correct: 0 },
{ q: "'पश्यति' शब्दस्य अर्थः कः?", a: ["देखता है", "खाता है", "सोता है", "लिखता है"], correct: 0 },
{ q: "'नरः' कः?", a: ["पुरुष", "स्त्री", "बालिका", "पशु"], correct: 0 },

{ q: "'बालिकाः' किम्?", a: ["एकवचन", "द्विवचन", "बहुवचन", "अव्यय"], correct: 2 },
{ q: "'फलानि' किम्?", a: ["एक फल", "दो फल", "अनेक फल", "कोई नहीं"], correct: 2 },
{ q: "'विद्यालयः' कः?", a: ["घर", "विद्यालय", "वन", "नदी"], correct: 1 },
{ q: "'पर्वतः' कः?", a: ["नदी", "पर्वत", "वन", "घर"], correct: 1 },
{ q: "'शिक्षकः' कः?", a: ["छात्र", "शिक्षक", "मित्र", "पिता"], correct: 1 },
{ q: "'छात्रः' कः?", a: ["शिक्षक", "छात्र", "पिता", "मित्र"], correct: 1 },
{ q: "'मित्रम्' किम्?", a: ["शत्रु", "मित्र", "पिता", "माता"], correct: 1 },
{ q: "'पिता' कः?", a: ["माता", "पिता", "भ्राता", "मित्र"], correct: 1 },
{ q: "'माता' का अर्थ?", a: ["पिता", "माता", "बहन", "पुत्र"], correct: 1 },
{ q: "'भ्राता' का अर्थ?", a: ["बहन", "भाई", "पिता", "मित्र"], correct: 1 },

{ q: "'बहिनि' का अर्थ?", a: ["बहन", "भाई", "माता", "मित्र"], correct: 0 },
{ q: "'क्रीडन्ति' शब्दः कः कालः?", a: ["वर्तमान", "भूत", "भविष्य", "आदेश"], correct: 0 },
{ q: "'लिखन्ति' का अर्थ?", a: ["लिखते हैं", "पढ़ते हैं", "खाते हैं", "सोते हैं"], correct: 0 },
{ q: "'खादन्ति' का अर्थ?", a: ["खाते हैं", "पीते हैं", "चलते हैं", "सोते हैं"], correct: 0 },
{ q: "'पश्यन्ति' का अर्थ?", a: ["देखते हैं", "खाते हैं", "सोते हैं", "लिखते हैं"], correct: 0 },
{ q: "'गच्छन्ति' का अर्थ?", a: ["जाते हैं", "आते हैं", "सोते हैं", "खाते हैं"], correct: 0 },
{ q: "'पिबन्ति' का अर्थ?", a: ["पीते हैं", "खाते हैं", "चलते हैं", "पढ़ते हैं"], correct: 0 },
{ q: "'सुन्दरम्' किम्?", a: ["संज्ञा", "क्रिया", "विशेषण", "सर्वनाम"], correct: 2 },
{ q: "'महान्' का अर्थ?", a: ["छोटा", "महान", "कमज़ोर", "धीमा"], correct: 1 },
{ q: "'लघु' का अर्थ?", a: ["भारी", "छोटा", "तेज़", "बड़ा"], correct: 1 }
],
};